/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package twopchat/core/cmd/lib2pcore */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"

#include "jni_callbacks.h"

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void goSetStorageDir(char* cDir);
extern int goInit(void);
extern int goSetNickname(char* cNick);
extern char* goEcho(char* cMsg);
extern char* goGetLocalIdentityJSON(void);
extern char* goGetLocalSeedMnemonic(void);
extern int goRestoreFromMnemonic(char* cNick, char* cMnemonic, char* cAbout);
extern char* goGetFingerprint(uint8_t* pubBytes, int length);
extern char* goGetSafetyNumber(uint8_t* myPub, int myPubLen, uint8_t* theirPub, int theirPubLen, uint8_t* myVerify, int myVerifyLen, uint8_t* theirVerify, int theirVerifyLen);
extern int goStartListener(int port);
extern int goStopListener(void);
extern int goConnectPeer(char* cEndpoint, char* cExpectedFP);
extern int goUpdatePeerNameMapping(char* cPeerFP, char* cNick);
extern char* goSendMessage(char* cPeerFP, char* cText);
extern char* goSendMessageBinary(char* cPeerFP, uint8_t* payload, int length);
extern char* goSendRawBytes(char* cPeerFP, uint8_t* payload, int length);
extern int goIsPeerOnline(char* cPeerFP);
extern char* goSendFile(char* cPeerFP, char* cFilePath, char* cMessageID, char* cFileName, char* cCaption, char* cEmoji);
extern int goCancelFile(char* cMsgID);
extern void goSetTorProxy(int enabled, char* cProxyAddr);
extern void goSetOnionAddress(char* cAddr);
extern char* goGetOnionAddress(void);
extern int goStartDiscovery(char* cTrackersJSON, char* cInfoHashesJSON, int port);
extern int goStopDiscovery(void);
extern int goUpdateTrackers(char* cTrackersJSON);
extern int goReloadIdentity(void);
extern int goAnnounceSelf(char* cInfoHashHex, int port);
extern int goProbePeer(char* cEndpointsJSON, char* cExpectedFP);
extern char* goGetLocalSigningPublicKey(void);
extern char* goSignGroupPayload(char* cCanonicalPayload);
extern int goVerifyGroupPayload(char* cVerificationKey, char* cCanonicalPayload, char* cSignature);
extern char* goGroupEncrypt(uint8_t* epochSecret, int secLen, uint8_t* authData, int adLen, uint8_t* plaintext, int ptLen);
extern void* goGroupDecrypt(uint8_t* epochSecret, int secLen, uint8_t* authData, int adLen, char* cNonceB64, char* cCiphertextB64, int* outLen);
extern int goTriggerNatTraversal(void);
extern char* goGetNatDiagnosticsJSON(void);
extern int goOnNetworkChanged(void);
extern void goFreeMemory(void* ptr);

#ifdef __cplusplus
}
#endif
