/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package twopchat/core/cmd/lib2pcore */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "main.go"

#include "jni_callbacks.h"

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void Java_com_example_twopchat_NativeBridge_nativeSetStorageDir(JNIEnv* env, jclass clazz, jstring jDir);
extern jboolean Java_com_example_twopchat_NativeBridge_nativeInit(JNIEnv* env, jclass clazz);
extern jstring Java_com_example_twopchat_NativeBridge_nativeEcho(JNIEnv* env, jclass clazz, jstring jMsg);
extern jstring Java_com_example_twopchat_NativeBridge_nativeGetLocalIdentityJSON(JNIEnv* env, jclass clazz);
extern jstring Java_com_example_twopchat_NativeBridge_nativeGetLocalSeedMnemonic(JNIEnv* env, jclass clazz);
extern jboolean Java_com_example_twopchat_NativeBridge_nativeRestoreFromMnemonic(JNIEnv* env, jclass clazz, jstring jNickname, jstring jMnemonic, jstring jAboutMe);
extern jstring Java_com_example_twopchat_NativeBridge_nativeGetFingerprint(JNIEnv* env, jclass clazz, jbyteArray jPub);
extern jstring Java_com_example_twopchat_NativeBridge_nativeGetSafetyNumber(JNIEnv* env, jclass clazz, jbyteArray jMyPub, jbyteArray jTheirPub, jbyteArray jMyVerify, jbyteArray jTheirVerify);
extern jboolean Java_com_example_twopchat_NativeBridge_nativeStartListener(JNIEnv* env, jclass clazz, jint jPort);
extern jboolean Java_com_example_twopchat_NativeBridge_nativeStopListener(JNIEnv* env, jclass clazz);
extern jboolean Java_com_example_twopchat_NativeBridge_nativeConnectPeer(JNIEnv* env, jclass clazz, jstring jEndpoint, jstring jExpectedFP);
extern jboolean Java_com_example_twopchat_NativeBridge_nativeUpdatePeerNameMapping(JNIEnv* env, jclass clazz, jstring jPeerFP, jstring jNickname);
extern jboolean Java_com_example_twopchat_NativeBridge_nativeSetNickname(JNIEnv* env, jclass clazz, jstring jNickname);
extern jstring Java_com_example_twopchat_NativeBridge_nativeSendMessage(JNIEnv* env, jclass clazz, jstring jPeerFP, jstring jText);
extern jboolean Java_com_example_twopchat_NativeBridge_nativeIsPeerOnline(JNIEnv* env, jclass clazz, jstring jPeerFP);
extern jstring Java_com_example_twopchat_NativeBridge_nativeSendFile(JNIEnv* env, jclass clazz, jstring jPeerFP, jstring jFilePath, jstring jMessageID, jstring jFileName, jstring jCaption, jstring jEmoji);
extern jboolean Java_com_example_twopchat_NativeBridge_nativeCancelFile(JNIEnv* env, jclass clazz, jstring jMessageID);
extern void Java_com_example_twopchat_NativeBridge_nativeSetTorProxy(JNIEnv* env, jclass clazz, jboolean jEnabled, jstring jProxyAddr);
extern void Java_com_example_twopchat_NativeBridge_nativeSetOnionAddress(JNIEnv* env, jclass clazz, jstring jAddr);
extern jstring Java_com_example_twopchat_NativeBridge_nativeGetOnionAddress(JNIEnv* env, jclass clazz);
extern jboolean Java_com_example_twopchat_NativeBridge_nativeStartDiscovery(JNIEnv* env, jclass clazz, jstring jTrackersJSON, jstring jInfoHashesJSON, jint jPort);
extern jboolean Java_com_example_twopchat_NativeBridge_nativeUpdateTrackers(JNIEnv* env, jclass clazz, jstring jTrackersJSON);
extern jboolean Java_com_example_twopchat_NativeBridge_nativeReloadIdentity(JNIEnv* env, jclass clazz);
extern jboolean Java_com_example_twopchat_NativeBridge_nativeStopDiscovery(JNIEnv* env, jclass clazz);
extern jboolean Java_com_example_twopchat_NativeBridge_nativeAnnounceSelf(JNIEnv* env, jclass clazz, jstring jInfoHashHex, jint jPort);
extern jboolean Java_com_example_twopchat_NativeBridge_nativeProbePeer(JNIEnv* env, jclass clazz, jstring jEndpointsJSON, jstring jExpectedFP);
extern void Java_com_example_twopchat_NativeBridge_nativeSetLocalYggdrasilIP(JNIEnv* env, jclass clazz, jstring jIP);
extern jstring Java_com_example_twopchat_NativeBridge_nativeSearchPeers(JNIEnv* env, jclass clazz, jstring jQuery, jstring jSharedCode, jstring jExpectedLiveName, jstring jExpectedFP, jstring jDirectCandidatesJSON);
extern jstring Java_com_example_twopchat_NativeBridge_nativeGetLocalSigningPublicKey(JNIEnv* env, jclass clazz);
extern jstring Java_com_example_twopchat_NativeBridge_nativeSignGroupPayload(JNIEnv* env, jclass clazz, jstring jCanonicalPayload);
extern jboolean Java_com_example_twopchat_NativeBridge_nativeVerifyGroupPayload(JNIEnv* env, jclass clazz, jstring jVerificationKey, jstring jCanonicalPayload, jstring jSignature);
extern jstring Java_com_example_twopchat_NativeBridge_nativeGroupEncrypt(JNIEnv* env, jclass clazz, jbyteArray jEpochSecret, jbyteArray jAuthenticatedData, jbyteArray jPlaintext);
extern jbyteArray Java_com_example_twopchat_NativeBridge_nativeGroupDecrypt(JNIEnv* env, jclass clazz, jbyteArray jEpochSecret, jbyteArray jAuthenticatedData, jstring jNonceBase64, jstring jCiphertextBase64);
extern jboolean Java_com_example_twopchat_NativeBridge_nativeTriggerNatTraversal(JNIEnv* env, jclass clazz);
extern jstring Java_com_example_twopchat_NativeBridge_nativeGetNatDiagnosticsJSON(JNIEnv* env, jclass clazz);
extern jboolean Java_com_example_twopchat_NativeBridge_nativeOnNetworkChanged(JNIEnv* env, jclass clazz);

#ifdef __cplusplus
}
#endif
